# reusable/deploy-infrastructure.yml - Deploys Azure infrastructure
name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Bicep template
        run: |
          RESOURCE_GROUP="rg-glasslewis-${{ inputs.environment }}"
          
          # Create resource group if it doesn't exist
          az group create --name $RESOURCE_GROUP --location northeurope
          
          # Deploy infrastructure
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --template-file infra/main.bicep \
            --parameters infra/params/${{ inputs.environment }}.bicepparam \
            --verbose
      
      - name: Get deployment outputs
        id: infra-outputs
        run: |
          RESOURCE_GROUP="rg-glasslewis-${{ inputs.environment }}"
          API_URL=$(az deployment group show --resource-group $RESOURCE_GROUP --name main --query properties.outputs.apiAppUrl.value -o tsv)
          CLIENT_URL=$(az deployment group show --resource-group $RESOURCE_GROUP --name main --query properties.outputs.clientAppUrl.value -o tsv)
          
          echo "api_url=${API_URL}" >> $GITHUB_OUTPUT
          echo "client_url=${CLIENT_URL}" >> $GITHUB_OUTPUT
